language: cpp
compiler: gcc
dist: trusty
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:  
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -qq

install: 
  - sudo sudo apt-get install -qq qt510base

script: 
  - mkdir build
  - cd build
  - cmake ..
  - make